# Generated by Django 2.1.1 on 2019-03-13 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='course',
            field=models.CharField(default='na', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='name',
            field=models.CharField(default='na', max_length=40),
            preserve_default=False,
        ),
    ]
