# Generated by Django 2.1.7 on 2019-03-29 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=20)),
                ('phone', models.IntegerField()),
                ('pincode', models.IntegerField()),
                ('state', models.CharField(max_length=20)),
                ('product', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
